/*
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MethUiModule extends AbstractMethUiModule {

	public MethUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
