/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ausgabe Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hvbargen.meth.meth.AusgabeStatement#getAusgabename <em>Ausgabename</em>}</li>
 *   <li>{@link hvbargen.meth.meth.AusgabeStatement#getEinheit <em>Einheit</em>}</li>
 *   <li>{@link hvbargen.meth.meth.AusgabeStatement#getBezeichnung <em>Bezeichnung</em>}</li>
 * </ul>
 *
 * @see hvbargen.meth.meth.MethPackage#getAusgabeStatement()
 * @model
 * @generated
 */
public interface AusgabeStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Ausgabename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ausgabename</em>' attribute.
   * @see #setAusgabename(String)
   * @see hvbargen.meth.meth.MethPackage#getAusgabeStatement_Ausgabename()
   * @model
   * @generated
   */
  String getAusgabename();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.AusgabeStatement#getAusgabename <em>Ausgabename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ausgabename</em>' attribute.
   * @see #getAusgabename()
   * @generated
   */
  void setAusgabename(String value);

  /**
   * Returns the value of the '<em><b>Einheit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Einheit</em>' containment reference.
   * @see #setEinheit(EinheitExpr)
   * @see hvbargen.meth.meth.MethPackage#getAusgabeStatement_Einheit()
   * @model containment="true"
   * @generated
   */
  EinheitExpr getEinheit();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.AusgabeStatement#getEinheit <em>Einheit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Einheit</em>' containment reference.
   * @see #getEinheit()
   * @generated
   */
  void setEinheit(EinheitExpr value);

  /**
   * Returns the value of the '<em><b>Bezeichnung</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bezeichnung</em>' attribute.
   * @see #setBezeichnung(String)
   * @see hvbargen.meth.meth.MethPackage#getAusgabeStatement_Bezeichnung()
   * @model
   * @generated
   */
  String getBezeichnung();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.AusgabeStatement#getBezeichnung <em>Bezeichnung</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bezeichnung</em>' attribute.
   * @see #getBezeichnung()
   * @generated
   */
  void setBezeichnung(String value);

} // AusgabeStatement
