/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Berechnung</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hvbargen.meth.meth.Berechnung#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see hvbargen.meth.meth.MethPackage#getBerechnung()
 * @model
 * @generated
 */
public interface Berechnung extends EObject
{
  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link hvbargen.meth.meth.BerechnungStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see hvbargen.meth.meth.MethPackage#getBerechnung_Statements()
   * @model containment="true"
   * @generated
   */
  EList<BerechnungStatement> getStatements();

} // Berechnung
