/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Deklaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hvbargen.meth.meth.MethPackage#getDeklaration()
 * @model
 * @generated
 */
public interface Deklaration extends EObject
{
} // Deklaration
