/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dezimalzahl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hvbargen.meth.meth.Dezimalzahl#getFwert <em>Fwert</em>}</li>
 * </ul>
 *
 * @see hvbargen.meth.meth.MethPackage#getDezimalzahl()
 * @model
 * @generated
 */
public interface Dezimalzahl extends Zahl
{
  /**
   * Returns the value of the '<em><b>Fwert</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fwert</em>' attribute.
   * @see #setFwert(String)
   * @see hvbargen.meth.meth.MethPackage#getDezimalzahl_Fwert()
   * @model
   * @generated
   */
  String getFwert();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.Dezimalzahl#getFwert <em>Fwert</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fwert</em>' attribute.
   * @see #getFwert()
   * @generated
   */
  void setFwert(String value);

} // Dezimalzahl
