/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Einheit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hvbargen.meth.meth.Einheit#getName <em>Name</em>}</li>
 *   <li>{@link hvbargen.meth.meth.Einheit#getRef <em>Ref</em>}</li>
 *   <li>{@link hvbargen.meth.meth.Einheit#getFaktor <em>Faktor</em>}</li>
 *   <li>{@link hvbargen.meth.meth.Einheit#getBasiseinheit <em>Basiseinheit</em>}</li>
 * </ul>
 *
 * @see hvbargen.meth.meth.MethPackage#getEinheit()
 * @model
 * @generated
 */
public interface Einheit extends Deklaration
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see hvbargen.meth.meth.MethPackage#getEinheit_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.Einheit#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(Dimension)
   * @see hvbargen.meth.meth.MethPackage#getEinheit_Ref()
   * @model
   * @generated
   */
  Dimension getRef();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.Einheit#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Dimension value);

  /**
   * Returns the value of the '<em><b>Faktor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Faktor</em>' containment reference.
   * @see #setFaktor(EinheitExpr)
   * @see hvbargen.meth.meth.MethPackage#getEinheit_Faktor()
   * @model containment="true"
   * @generated
   */
  EinheitExpr getFaktor();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.Einheit#getFaktor <em>Faktor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Faktor</em>' containment reference.
   * @see #getFaktor()
   * @generated
   */
  void setFaktor(EinheitExpr value);

  /**
   * Returns the value of the '<em><b>Basiseinheit</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Basiseinheit</em>' reference.
   * @see #setBasiseinheit(Einheit)
   * @see hvbargen.meth.meth.MethPackage#getEinheit_Basiseinheit()
   * @model
   * @generated
   */
  Einheit getBasiseinheit();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.Einheit#getBasiseinheit <em>Basiseinheit</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Basiseinheit</em>' reference.
   * @see #getBasiseinheit()
   * @generated
   */
  void setBasiseinheit(Einheit value);

} // Einheit
