/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Formel</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hvbargen.meth.meth.MethPackage#getFormel()
 * @model
 * @generated
 */
public interface Formel extends EObject
{
} // Formel
