/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ganzzahl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hvbargen.meth.meth.Ganzzahl#getIwert <em>Iwert</em>}</li>
 * </ul>
 *
 * @see hvbargen.meth.meth.MethPackage#getGanzzahl()
 * @model
 * @generated
 */
public interface Ganzzahl extends Zahl
{
  /**
   * Returns the value of the '<em><b>Iwert</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iwert</em>' attribute.
   * @see #setIwert(String)
   * @see hvbargen.meth.meth.MethPackage#getGanzzahl_Iwert()
   * @model
   * @generated
   */
  String getIwert();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.Ganzzahl#getIwert <em>Iwert</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Iwert</em>' attribute.
   * @see #getIwert()
   * @generated
   */
  void setIwert(String value);

} // Ganzzahl
