/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gegeben Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hvbargen.meth.meth.GegebenStatement#getEingabename <em>Eingabename</em>}</li>
 *   <li>{@link hvbargen.meth.meth.GegebenStatement#getEinheit <em>Einheit</em>}</li>
 *   <li>{@link hvbargen.meth.meth.GegebenStatement#getRefMethode <em>Ref Methode</em>}</li>
 *   <li>{@link hvbargen.meth.meth.GegebenStatement#getBezeichnung <em>Bezeichnung</em>}</li>
 * </ul>
 *
 * @see hvbargen.meth.meth.MethPackage#getGegebenStatement()
 * @model
 * @generated
 */
public interface GegebenStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Eingabename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Eingabename</em>' attribute.
   * @see #setEingabename(String)
   * @see hvbargen.meth.meth.MethPackage#getGegebenStatement_Eingabename()
   * @model
   * @generated
   */
  String getEingabename();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.GegebenStatement#getEingabename <em>Eingabename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Eingabename</em>' attribute.
   * @see #getEingabename()
   * @generated
   */
  void setEingabename(String value);

  /**
   * Returns the value of the '<em><b>Einheit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Einheit</em>' containment reference.
   * @see #setEinheit(EinheitExpr)
   * @see hvbargen.meth.meth.MethPackage#getGegebenStatement_Einheit()
   * @model containment="true"
   * @generated
   */
  EinheitExpr getEinheit();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.GegebenStatement#getEinheit <em>Einheit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Einheit</em>' containment reference.
   * @see #getEinheit()
   * @generated
   */
  void setEinheit(EinheitExpr value);

  /**
   * Returns the value of the '<em><b>Ref Methode</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref Methode</em>' reference.
   * @see #setRefMethode(Methode)
   * @see hvbargen.meth.meth.MethPackage#getGegebenStatement_RefMethode()
   * @model
   * @generated
   */
  Methode getRefMethode();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.GegebenStatement#getRefMethode <em>Ref Methode</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref Methode</em>' reference.
   * @see #getRefMethode()
   * @generated
   */
  void setRefMethode(Methode value);

  /**
   * Returns the value of the '<em><b>Bezeichnung</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bezeichnung</em>' attribute.
   * @see #setBezeichnung(String)
   * @see hvbargen.meth.meth.MethPackage#getGegebenStatement_Bezeichnung()
   * @model
   * @generated
   */
  String getBezeichnung();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.GegebenStatement#getBezeichnung <em>Bezeichnung</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bezeichnung</em>' attribute.
   * @see #getBezeichnung()
   * @generated
   */
  void setBezeichnung(String value);

} // GegebenStatement
