/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see hvbargen.meth.meth.MethPackage
 * @generated
 */
public interface MethFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MethFactory eINSTANCE = hvbargen.meth.meth.impl.MethFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Einheitensystem</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Einheitensystem</em>'.
   * @generated
   */
  Einheitensystem createEinheitensystem();

  /**
   * Returns a new object of class '<em>Deklaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Deklaration</em>'.
   * @generated
   */
  Deklaration createDeklaration();

  /**
   * Returns a new object of class '<em>Dimension</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dimension</em>'.
   * @generated
   */
  Dimension createDimension();

  /**
   * Returns a new object of class '<em>Dimension Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dimension Expr</em>'.
   * @generated
   */
  DimensionExpr createDimensionExpr();

  /**
   * Returns a new object of class '<em>Einheit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Einheit</em>'.
   * @generated
   */
  Einheit createEinheit();

  /**
   * Returns a new object of class '<em>Umrechnung</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Umrechnung</em>'.
   * @generated
   */
  Umrechnung createUmrechnung();

  /**
   * Returns a new object of class '<em>Konstante</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Konstante</em>'.
   * @generated
   */
  Konstante createKonstante();

  /**
   * Returns a new object of class '<em>Zahl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Zahl</em>'.
   * @generated
   */
  Zahl createZahl();

  /**
   * Returns a new object of class '<em>Ganzzahl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ganzzahl</em>'.
   * @generated
   */
  Ganzzahl createGanzzahl();

  /**
   * Returns a new object of class '<em>Dezimalzahl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dezimalzahl</em>'.
   * @generated
   */
  Dezimalzahl createDezimalzahl();

  /**
   * Returns a new object of class '<em>Einheit Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Einheit Expr</em>'.
   * @generated
   */
  EinheitExpr createEinheitExpr();

  /**
   * Returns a new object of class '<em>Methode</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Methode</em>'.
   * @generated
   */
  Methode createMethode();

  /**
   * Returns a new object of class '<em>Gegeben</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Gegeben</em>'.
   * @generated
   */
  Gegeben createGegeben();

  /**
   * Returns a new object of class '<em>Eingabe</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Eingabe</em>'.
   * @generated
   */
  Eingabe createEingabe();

  /**
   * Returns a new object of class '<em>Berechnung</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Berechnung</em>'.
   * @generated
   */
  Berechnung createBerechnung();

  /**
   * Returns a new object of class '<em>Ausgabe</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ausgabe</em>'.
   * @generated
   */
  Ausgabe createAusgabe();

  /**
   * Returns a new object of class '<em>Gegeben Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Gegeben Statement</em>'.
   * @generated
   */
  GegebenStatement createGegebenStatement();

  /**
   * Returns a new object of class '<em>Eingabe Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Eingabe Statement</em>'.
   * @generated
   */
  EingabeStatement createEingabeStatement();

  /**
   * Returns a new object of class '<em>Berechnung Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Berechnung Statement</em>'.
   * @generated
   */
  BerechnungStatement createBerechnungStatement();

  /**
   * Returns a new object of class '<em>Ausgabe Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ausgabe Statement</em>'.
   * @generated
   */
  AusgabeStatement createAusgabeStatement();

  /**
   * Returns a new object of class '<em>Formel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Formel</em>'.
   * @generated
   */
  Formel createFormel();

  /**
   * Returns a new object of class '<em>Text Formel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Text Formel</em>'.
   * @generated
   */
  TextFormel createTextFormel();

  /**
   * Returns a new object of class '<em>Num Formel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Num Formel</em>'.
   * @generated
   */
  NumFormel createNumFormel();

  /**
   * Returns a new object of class '<em>Dimension Multiplikation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dimension Multiplikation</em>'.
   * @generated
   */
  DimensionMultiplikation createDimensionMultiplikation();

  /**
   * Returns a new object of class '<em>Einheit Addition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Einheit Addition</em>'.
   * @generated
   */
  EinheitAddition createEinheitAddition();

  /**
   * Returns a new object of class '<em>Einheit Multiplikation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Einheit Multiplikation</em>'.
   * @generated
   */
  EinheitMultiplikation createEinheitMultiplikation();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MethPackage getMethPackage();

} //MethFactory
