/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see hvbargen.meth.meth.MethFactory
 * @model kind="package"
 * @generated
 */
public interface MethPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "meth";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.meth.hvbargen/Meth";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "meth";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MethPackage eINSTANCE = hvbargen.meth.meth.impl.MethPackageImpl.init();

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.ModelImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Einheitensystem</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__EINHEITENSYSTEM = 0;

  /**
   * The feature id for the '<em><b>Methoden</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__METHODEN = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.EinheitensystemImpl <em>Einheitensystem</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.EinheitensystemImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getEinheitensystem()
   * @generated
   */
  int EINHEITENSYSTEM = 1;

  /**
   * The feature id for the '<em><b>Deklarationen</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEITENSYSTEM__DEKLARATIONEN = 0;

  /**
   * The number of structural features of the '<em>Einheitensystem</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEITENSYSTEM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.DeklarationImpl <em>Deklaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.DeklarationImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getDeklaration()
   * @generated
   */
  int DEKLARATION = 2;

  /**
   * The number of structural features of the '<em>Deklaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEKLARATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.DimensionImpl <em>Dimension</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.DimensionImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getDimension()
   * @generated
   */
  int DIMENSION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMENSION__NAME = DEKLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Basis</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMENSION__BASIS = DEKLARATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Dimension</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMENSION_FEATURE_COUNT = DEKLARATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.DimensionExprImpl <em>Dimension Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.DimensionExprImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getDimensionExpr()
   * @generated
   */
  int DIMENSION_EXPR = 4;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMENSION_EXPR__REF = 0;

  /**
   * The number of structural features of the '<em>Dimension Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMENSION_EXPR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.EinheitImpl <em>Einheit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.EinheitImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getEinheit()
   * @generated
   */
  int EINHEIT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT__NAME = DEKLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT__REF = DEKLARATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Faktor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT__FAKTOR = DEKLARATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Basiseinheit</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT__BASISEINHEIT = DEKLARATION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Einheit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT_FEATURE_COUNT = DEKLARATION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.UmrechnungImpl <em>Umrechnung</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.UmrechnungImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getUmrechnung()
   * @generated
   */
  int UMRECHNUNG = 6;

  /**
   * The feature id for the '<em><b>Varname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UMRECHNUNG__VARNAME = DEKLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Von Einheit</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UMRECHNUNG__VON_EINHEIT = DEKLARATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Ausdruck</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UMRECHNUNG__AUSDRUCK = DEKLARATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Nach Einheit</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UMRECHNUNG__NACH_EINHEIT = DEKLARATION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Umrechnung</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UMRECHNUNG_FEATURE_COUNT = DEKLARATION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.KonstanteImpl <em>Konstante</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.KonstanteImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getKonstante()
   * @generated
   */
  int KONSTANTE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KONSTANTE__NAME = DEKLARATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ausdruck</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KONSTANTE__AUSDRUCK = DEKLARATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Konstante</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KONSTANTE_FEATURE_COUNT = DEKLARATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.EinheitExprImpl <em>Einheit Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.EinheitExprImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getEinheitExpr()
   * @generated
   */
  int EINHEIT_EXPR = 11;

  /**
   * The feature id for the '<em><b>Varref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT_EXPR__VARREF = 0;

  /**
   * The number of structural features of the '<em>Einheit Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT_EXPR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.ZahlImpl <em>Zahl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.ZahlImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getZahl()
   * @generated
   */
  int ZAHL = 8;

  /**
   * The feature id for the '<em><b>Varref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZAHL__VARREF = EINHEIT_EXPR__VARREF;

  /**
   * The number of structural features of the '<em>Zahl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZAHL_FEATURE_COUNT = EINHEIT_EXPR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.GanzzahlImpl <em>Ganzzahl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.GanzzahlImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getGanzzahl()
   * @generated
   */
  int GANZZAHL = 9;

  /**
   * The feature id for the '<em><b>Varref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GANZZAHL__VARREF = ZAHL__VARREF;

  /**
   * The feature id for the '<em><b>Iwert</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GANZZAHL__IWERT = ZAHL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ganzzahl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GANZZAHL_FEATURE_COUNT = ZAHL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.DezimalzahlImpl <em>Dezimalzahl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.DezimalzahlImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getDezimalzahl()
   * @generated
   */
  int DEZIMALZAHL = 10;

  /**
   * The feature id for the '<em><b>Varref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEZIMALZAHL__VARREF = ZAHL__VARREF;

  /**
   * The feature id for the '<em><b>Fwert</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEZIMALZAHL__FWERT = ZAHL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Dezimalzahl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEZIMALZAHL_FEATURE_COUNT = ZAHL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.MethodeImpl <em>Methode</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.MethodeImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getMethode()
   * @generated
   */
  int METHODE = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHODE__NAME = 0;

  /**
   * The feature id for the '<em><b>Bezeichnung</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHODE__BEZEICHNUNG = 1;

  /**
   * The feature id for the '<em><b>Ablauf</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHODE__ABLAUF = 2;

  /**
   * The number of structural features of the '<em>Methode</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHODE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.GegebenImpl <em>Gegeben</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.GegebenImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getGegeben()
   * @generated
   */
  int GEGEBEN = 13;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEGEBEN__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Gegeben</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEGEBEN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.EingabeImpl <em>Eingabe</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.EingabeImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getEingabe()
   * @generated
   */
  int EINGABE = 14;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINGABE__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Eingabe</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINGABE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.BerechnungImpl <em>Berechnung</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.BerechnungImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getBerechnung()
   * @generated
   */
  int BERECHNUNG = 15;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BERECHNUNG__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Berechnung</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BERECHNUNG_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.AusgabeImpl <em>Ausgabe</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.AusgabeImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getAusgabe()
   * @generated
   */
  int AUSGABE = 16;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUSGABE__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Ausgabe</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUSGABE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.GegebenStatementImpl <em>Gegeben Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.GegebenStatementImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getGegebenStatement()
   * @generated
   */
  int GEGEBEN_STATEMENT = 17;

  /**
   * The feature id for the '<em><b>Eingabename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEGEBEN_STATEMENT__EINGABENAME = 0;

  /**
   * The feature id for the '<em><b>Einheit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEGEBEN_STATEMENT__EINHEIT = 1;

  /**
   * The feature id for the '<em><b>Ref Methode</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEGEBEN_STATEMENT__REF_METHODE = 2;

  /**
   * The feature id for the '<em><b>Bezeichnung</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEGEBEN_STATEMENT__BEZEICHNUNG = 3;

  /**
   * The number of structural features of the '<em>Gegeben Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GEGEBEN_STATEMENT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.EingabeStatementImpl <em>Eingabe Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.EingabeStatementImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getEingabeStatement()
   * @generated
   */
  int EINGABE_STATEMENT = 18;

  /**
   * The feature id for the '<em><b>Eingabename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINGABE_STATEMENT__EINGABENAME = 0;

  /**
   * The feature id for the '<em><b>Einheit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINGABE_STATEMENT__EINHEIT = 1;

  /**
   * The feature id for the '<em><b>Bezeichnung</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINGABE_STATEMENT__BEZEICHNUNG = 2;

  /**
   * The number of structural features of the '<em>Eingabe Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINGABE_STATEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.BerechnungStatementImpl <em>Berechnung Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.BerechnungStatementImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getBerechnungStatement()
   * @generated
   */
  int BERECHNUNG_STATEMENT = 19;

  /**
   * The feature id for the '<em><b>Berechnungname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BERECHNUNG_STATEMENT__BERECHNUNGNAME = 0;

  /**
   * The feature id for the '<em><b>Formel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BERECHNUNG_STATEMENT__FORMEL = 1;

  /**
   * The feature id for the '<em><b>Bezeichnung</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BERECHNUNG_STATEMENT__BEZEICHNUNG = 2;

  /**
   * The number of structural features of the '<em>Berechnung Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BERECHNUNG_STATEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.AusgabeStatementImpl <em>Ausgabe Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.AusgabeStatementImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getAusgabeStatement()
   * @generated
   */
  int AUSGABE_STATEMENT = 20;

  /**
   * The feature id for the '<em><b>Ausgabename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUSGABE_STATEMENT__AUSGABENAME = 0;

  /**
   * The feature id for the '<em><b>Einheit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUSGABE_STATEMENT__EINHEIT = 1;

  /**
   * The feature id for the '<em><b>Bezeichnung</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUSGABE_STATEMENT__BEZEICHNUNG = 2;

  /**
   * The number of structural features of the '<em>Ausgabe Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUSGABE_STATEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.FormelImpl <em>Formel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.FormelImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getFormel()
   * @generated
   */
  int FORMEL = 21;

  /**
   * The number of structural features of the '<em>Formel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMEL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.TextFormelImpl <em>Text Formel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.TextFormelImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getTextFormel()
   * @generated
   */
  int TEXT_FORMEL = 22;

  /**
   * The feature id for the '<em><b>Tformel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FORMEL__TFORMEL = FORMEL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Text Formel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_FORMEL_FEATURE_COUNT = FORMEL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.NumFormelImpl <em>Num Formel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.NumFormelImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getNumFormel()
   * @generated
   */
  int NUM_FORMEL = 23;

  /**
   * The feature id for the '<em><b>Nformel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUM_FORMEL__NFORMEL = FORMEL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Num Formel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUM_FORMEL_FEATURE_COUNT = FORMEL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.DimensionMultiplikationImpl <em>Dimension Multiplikation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.DimensionMultiplikationImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getDimensionMultiplikation()
   * @generated
   */
  int DIMENSION_MULTIPLIKATION = 24;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMENSION_MULTIPLIKATION__REF = DIMENSION_EXPR__REF;

  /**
   * The feature id for the '<em><b>Links</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMENSION_MULTIPLIKATION__LINKS = DIMENSION_EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMENSION_MULTIPLIKATION__OPERATOR = DIMENSION_EXPR_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Rechts</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMENSION_MULTIPLIKATION__RECHTS = DIMENSION_EXPR_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Dimension Multiplikation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMENSION_MULTIPLIKATION_FEATURE_COUNT = DIMENSION_EXPR_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.EinheitAdditionImpl <em>Einheit Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.EinheitAdditionImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getEinheitAddition()
   * @generated
   */
  int EINHEIT_ADDITION = 25;

  /**
   * The feature id for the '<em><b>Varref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT_ADDITION__VARREF = EINHEIT_EXPR__VARREF;

  /**
   * The feature id for the '<em><b>Links</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT_ADDITION__LINKS = EINHEIT_EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT_ADDITION__OPERATOR = EINHEIT_EXPR_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Rechts</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT_ADDITION__RECHTS = EINHEIT_EXPR_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Einheit Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT_ADDITION_FEATURE_COUNT = EINHEIT_EXPR_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link hvbargen.meth.meth.impl.EinheitMultiplikationImpl <em>Einheit Multiplikation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hvbargen.meth.meth.impl.EinheitMultiplikationImpl
   * @see hvbargen.meth.meth.impl.MethPackageImpl#getEinheitMultiplikation()
   * @generated
   */
  int EINHEIT_MULTIPLIKATION = 26;

  /**
   * The feature id for the '<em><b>Varref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT_MULTIPLIKATION__VARREF = EINHEIT_EXPR__VARREF;

  /**
   * The feature id for the '<em><b>Links</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT_MULTIPLIKATION__LINKS = EINHEIT_EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT_MULTIPLIKATION__OPERATOR = EINHEIT_EXPR_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Rechts</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT_MULTIPLIKATION__RECHTS = EINHEIT_EXPR_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Einheit Multiplikation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EINHEIT_MULTIPLIKATION_FEATURE_COUNT = EINHEIT_EXPR_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see hvbargen.meth.meth.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link hvbargen.meth.meth.Model#getEinheitensystem <em>Einheitensystem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Einheitensystem</em>'.
   * @see hvbargen.meth.meth.Model#getEinheitensystem()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Einheitensystem();

  /**
   * Returns the meta object for the containment reference list '{@link hvbargen.meth.meth.Model#getMethoden <em>Methoden</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Methoden</em>'.
   * @see hvbargen.meth.meth.Model#getMethoden()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Methoden();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.Einheitensystem <em>Einheitensystem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Einheitensystem</em>'.
   * @see hvbargen.meth.meth.Einheitensystem
   * @generated
   */
  EClass getEinheitensystem();

  /**
   * Returns the meta object for the containment reference list '{@link hvbargen.meth.meth.Einheitensystem#getDeklarationen <em>Deklarationen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Deklarationen</em>'.
   * @see hvbargen.meth.meth.Einheitensystem#getDeklarationen()
   * @see #getEinheitensystem()
   * @generated
   */
  EReference getEinheitensystem_Deklarationen();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.Deklaration <em>Deklaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Deklaration</em>'.
   * @see hvbargen.meth.meth.Deklaration
   * @generated
   */
  EClass getDeklaration();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.Dimension <em>Dimension</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dimension</em>'.
   * @see hvbargen.meth.meth.Dimension
   * @generated
   */
  EClass getDimension();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.Dimension#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see hvbargen.meth.meth.Dimension#getName()
   * @see #getDimension()
   * @generated
   */
  EAttribute getDimension_Name();

  /**
   * Returns the meta object for the containment reference '{@link hvbargen.meth.meth.Dimension#getBasis <em>Basis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Basis</em>'.
   * @see hvbargen.meth.meth.Dimension#getBasis()
   * @see #getDimension()
   * @generated
   */
  EReference getDimension_Basis();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.DimensionExpr <em>Dimension Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dimension Expr</em>'.
   * @see hvbargen.meth.meth.DimensionExpr
   * @generated
   */
  EClass getDimensionExpr();

  /**
   * Returns the meta object for the reference '{@link hvbargen.meth.meth.DimensionExpr#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see hvbargen.meth.meth.DimensionExpr#getRef()
   * @see #getDimensionExpr()
   * @generated
   */
  EReference getDimensionExpr_Ref();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.Einheit <em>Einheit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Einheit</em>'.
   * @see hvbargen.meth.meth.Einheit
   * @generated
   */
  EClass getEinheit();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.Einheit#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see hvbargen.meth.meth.Einheit#getName()
   * @see #getEinheit()
   * @generated
   */
  EAttribute getEinheit_Name();

  /**
   * Returns the meta object for the reference '{@link hvbargen.meth.meth.Einheit#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see hvbargen.meth.meth.Einheit#getRef()
   * @see #getEinheit()
   * @generated
   */
  EReference getEinheit_Ref();

  /**
   * Returns the meta object for the containment reference '{@link hvbargen.meth.meth.Einheit#getFaktor <em>Faktor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Faktor</em>'.
   * @see hvbargen.meth.meth.Einheit#getFaktor()
   * @see #getEinheit()
   * @generated
   */
  EReference getEinheit_Faktor();

  /**
   * Returns the meta object for the reference '{@link hvbargen.meth.meth.Einheit#getBasiseinheit <em>Basiseinheit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Basiseinheit</em>'.
   * @see hvbargen.meth.meth.Einheit#getBasiseinheit()
   * @see #getEinheit()
   * @generated
   */
  EReference getEinheit_Basiseinheit();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.Umrechnung <em>Umrechnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Umrechnung</em>'.
   * @see hvbargen.meth.meth.Umrechnung
   * @generated
   */
  EClass getUmrechnung();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.Umrechnung#getVarname <em>Varname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Varname</em>'.
   * @see hvbargen.meth.meth.Umrechnung#getVarname()
   * @see #getUmrechnung()
   * @generated
   */
  EAttribute getUmrechnung_Varname();

  /**
   * Returns the meta object for the reference '{@link hvbargen.meth.meth.Umrechnung#getVonEinheit <em>Von Einheit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Von Einheit</em>'.
   * @see hvbargen.meth.meth.Umrechnung#getVonEinheit()
   * @see #getUmrechnung()
   * @generated
   */
  EReference getUmrechnung_VonEinheit();

  /**
   * Returns the meta object for the containment reference '{@link hvbargen.meth.meth.Umrechnung#getAusdruck <em>Ausdruck</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ausdruck</em>'.
   * @see hvbargen.meth.meth.Umrechnung#getAusdruck()
   * @see #getUmrechnung()
   * @generated
   */
  EReference getUmrechnung_Ausdruck();

  /**
   * Returns the meta object for the reference '{@link hvbargen.meth.meth.Umrechnung#getNachEinheit <em>Nach Einheit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Nach Einheit</em>'.
   * @see hvbargen.meth.meth.Umrechnung#getNachEinheit()
   * @see #getUmrechnung()
   * @generated
   */
  EReference getUmrechnung_NachEinheit();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.Konstante <em>Konstante</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Konstante</em>'.
   * @see hvbargen.meth.meth.Konstante
   * @generated
   */
  EClass getKonstante();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.Konstante#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see hvbargen.meth.meth.Konstante#getName()
   * @see #getKonstante()
   * @generated
   */
  EAttribute getKonstante_Name();

  /**
   * Returns the meta object for the containment reference '{@link hvbargen.meth.meth.Konstante#getAusdruck <em>Ausdruck</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ausdruck</em>'.
   * @see hvbargen.meth.meth.Konstante#getAusdruck()
   * @see #getKonstante()
   * @generated
   */
  EReference getKonstante_Ausdruck();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.Zahl <em>Zahl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Zahl</em>'.
   * @see hvbargen.meth.meth.Zahl
   * @generated
   */
  EClass getZahl();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.Ganzzahl <em>Ganzzahl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ganzzahl</em>'.
   * @see hvbargen.meth.meth.Ganzzahl
   * @generated
   */
  EClass getGanzzahl();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.Ganzzahl#getIwert <em>Iwert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Iwert</em>'.
   * @see hvbargen.meth.meth.Ganzzahl#getIwert()
   * @see #getGanzzahl()
   * @generated
   */
  EAttribute getGanzzahl_Iwert();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.Dezimalzahl <em>Dezimalzahl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dezimalzahl</em>'.
   * @see hvbargen.meth.meth.Dezimalzahl
   * @generated
   */
  EClass getDezimalzahl();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.Dezimalzahl#getFwert <em>Fwert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fwert</em>'.
   * @see hvbargen.meth.meth.Dezimalzahl#getFwert()
   * @see #getDezimalzahl()
   * @generated
   */
  EAttribute getDezimalzahl_Fwert();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.EinheitExpr <em>Einheit Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Einheit Expr</em>'.
   * @see hvbargen.meth.meth.EinheitExpr
   * @generated
   */
  EClass getEinheitExpr();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.EinheitExpr#getVarref <em>Varref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Varref</em>'.
   * @see hvbargen.meth.meth.EinheitExpr#getVarref()
   * @see #getEinheitExpr()
   * @generated
   */
  EAttribute getEinheitExpr_Varref();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.Methode <em>Methode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Methode</em>'.
   * @see hvbargen.meth.meth.Methode
   * @generated
   */
  EClass getMethode();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.Methode#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see hvbargen.meth.meth.Methode#getName()
   * @see #getMethode()
   * @generated
   */
  EAttribute getMethode_Name();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.Methode#getBezeichnung <em>Bezeichnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bezeichnung</em>'.
   * @see hvbargen.meth.meth.Methode#getBezeichnung()
   * @see #getMethode()
   * @generated
   */
  EAttribute getMethode_Bezeichnung();

  /**
   * Returns the meta object for the containment reference list '{@link hvbargen.meth.meth.Methode#getAblauf <em>Ablauf</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ablauf</em>'.
   * @see hvbargen.meth.meth.Methode#getAblauf()
   * @see #getMethode()
   * @generated
   */
  EReference getMethode_Ablauf();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.Gegeben <em>Gegeben</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Gegeben</em>'.
   * @see hvbargen.meth.meth.Gegeben
   * @generated
   */
  EClass getGegeben();

  /**
   * Returns the meta object for the containment reference list '{@link hvbargen.meth.meth.Gegeben#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see hvbargen.meth.meth.Gegeben#getStatements()
   * @see #getGegeben()
   * @generated
   */
  EReference getGegeben_Statements();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.Eingabe <em>Eingabe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Eingabe</em>'.
   * @see hvbargen.meth.meth.Eingabe
   * @generated
   */
  EClass getEingabe();

  /**
   * Returns the meta object for the containment reference list '{@link hvbargen.meth.meth.Eingabe#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see hvbargen.meth.meth.Eingabe#getStatements()
   * @see #getEingabe()
   * @generated
   */
  EReference getEingabe_Statements();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.Berechnung <em>Berechnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Berechnung</em>'.
   * @see hvbargen.meth.meth.Berechnung
   * @generated
   */
  EClass getBerechnung();

  /**
   * Returns the meta object for the containment reference list '{@link hvbargen.meth.meth.Berechnung#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see hvbargen.meth.meth.Berechnung#getStatements()
   * @see #getBerechnung()
   * @generated
   */
  EReference getBerechnung_Statements();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.Ausgabe <em>Ausgabe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ausgabe</em>'.
   * @see hvbargen.meth.meth.Ausgabe
   * @generated
   */
  EClass getAusgabe();

  /**
   * Returns the meta object for the containment reference list '{@link hvbargen.meth.meth.Ausgabe#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see hvbargen.meth.meth.Ausgabe#getStatements()
   * @see #getAusgabe()
   * @generated
   */
  EReference getAusgabe_Statements();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.GegebenStatement <em>Gegeben Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Gegeben Statement</em>'.
   * @see hvbargen.meth.meth.GegebenStatement
   * @generated
   */
  EClass getGegebenStatement();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.GegebenStatement#getEingabename <em>Eingabename</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Eingabename</em>'.
   * @see hvbargen.meth.meth.GegebenStatement#getEingabename()
   * @see #getGegebenStatement()
   * @generated
   */
  EAttribute getGegebenStatement_Eingabename();

  /**
   * Returns the meta object for the containment reference '{@link hvbargen.meth.meth.GegebenStatement#getEinheit <em>Einheit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Einheit</em>'.
   * @see hvbargen.meth.meth.GegebenStatement#getEinheit()
   * @see #getGegebenStatement()
   * @generated
   */
  EReference getGegebenStatement_Einheit();

  /**
   * Returns the meta object for the reference '{@link hvbargen.meth.meth.GegebenStatement#getRefMethode <em>Ref Methode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref Methode</em>'.
   * @see hvbargen.meth.meth.GegebenStatement#getRefMethode()
   * @see #getGegebenStatement()
   * @generated
   */
  EReference getGegebenStatement_RefMethode();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.GegebenStatement#getBezeichnung <em>Bezeichnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bezeichnung</em>'.
   * @see hvbargen.meth.meth.GegebenStatement#getBezeichnung()
   * @see #getGegebenStatement()
   * @generated
   */
  EAttribute getGegebenStatement_Bezeichnung();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.EingabeStatement <em>Eingabe Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Eingabe Statement</em>'.
   * @see hvbargen.meth.meth.EingabeStatement
   * @generated
   */
  EClass getEingabeStatement();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.EingabeStatement#getEingabename <em>Eingabename</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Eingabename</em>'.
   * @see hvbargen.meth.meth.EingabeStatement#getEingabename()
   * @see #getEingabeStatement()
   * @generated
   */
  EAttribute getEingabeStatement_Eingabename();

  /**
   * Returns the meta object for the containment reference '{@link hvbargen.meth.meth.EingabeStatement#getEinheit <em>Einheit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Einheit</em>'.
   * @see hvbargen.meth.meth.EingabeStatement#getEinheit()
   * @see #getEingabeStatement()
   * @generated
   */
  EReference getEingabeStatement_Einheit();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.EingabeStatement#getBezeichnung <em>Bezeichnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bezeichnung</em>'.
   * @see hvbargen.meth.meth.EingabeStatement#getBezeichnung()
   * @see #getEingabeStatement()
   * @generated
   */
  EAttribute getEingabeStatement_Bezeichnung();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.BerechnungStatement <em>Berechnung Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Berechnung Statement</em>'.
   * @see hvbargen.meth.meth.BerechnungStatement
   * @generated
   */
  EClass getBerechnungStatement();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.BerechnungStatement#getBerechnungname <em>Berechnungname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Berechnungname</em>'.
   * @see hvbargen.meth.meth.BerechnungStatement#getBerechnungname()
   * @see #getBerechnungStatement()
   * @generated
   */
  EAttribute getBerechnungStatement_Berechnungname();

  /**
   * Returns the meta object for the containment reference '{@link hvbargen.meth.meth.BerechnungStatement#getFormel <em>Formel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Formel</em>'.
   * @see hvbargen.meth.meth.BerechnungStatement#getFormel()
   * @see #getBerechnungStatement()
   * @generated
   */
  EReference getBerechnungStatement_Formel();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.BerechnungStatement#getBezeichnung <em>Bezeichnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bezeichnung</em>'.
   * @see hvbargen.meth.meth.BerechnungStatement#getBezeichnung()
   * @see #getBerechnungStatement()
   * @generated
   */
  EAttribute getBerechnungStatement_Bezeichnung();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.AusgabeStatement <em>Ausgabe Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ausgabe Statement</em>'.
   * @see hvbargen.meth.meth.AusgabeStatement
   * @generated
   */
  EClass getAusgabeStatement();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.AusgabeStatement#getAusgabename <em>Ausgabename</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ausgabename</em>'.
   * @see hvbargen.meth.meth.AusgabeStatement#getAusgabename()
   * @see #getAusgabeStatement()
   * @generated
   */
  EAttribute getAusgabeStatement_Ausgabename();

  /**
   * Returns the meta object for the containment reference '{@link hvbargen.meth.meth.AusgabeStatement#getEinheit <em>Einheit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Einheit</em>'.
   * @see hvbargen.meth.meth.AusgabeStatement#getEinheit()
   * @see #getAusgabeStatement()
   * @generated
   */
  EReference getAusgabeStatement_Einheit();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.AusgabeStatement#getBezeichnung <em>Bezeichnung</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bezeichnung</em>'.
   * @see hvbargen.meth.meth.AusgabeStatement#getBezeichnung()
   * @see #getAusgabeStatement()
   * @generated
   */
  EAttribute getAusgabeStatement_Bezeichnung();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.Formel <em>Formel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Formel</em>'.
   * @see hvbargen.meth.meth.Formel
   * @generated
   */
  EClass getFormel();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.TextFormel <em>Text Formel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Formel</em>'.
   * @see hvbargen.meth.meth.TextFormel
   * @generated
   */
  EClass getTextFormel();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.TextFormel#getTformel <em>Tformel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tformel</em>'.
   * @see hvbargen.meth.meth.TextFormel#getTformel()
   * @see #getTextFormel()
   * @generated
   */
  EAttribute getTextFormel_Tformel();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.NumFormel <em>Num Formel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Num Formel</em>'.
   * @see hvbargen.meth.meth.NumFormel
   * @generated
   */
  EClass getNumFormel();

  /**
   * Returns the meta object for the containment reference '{@link hvbargen.meth.meth.NumFormel#getNformel <em>Nformel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nformel</em>'.
   * @see hvbargen.meth.meth.NumFormel#getNformel()
   * @see #getNumFormel()
   * @generated
   */
  EReference getNumFormel_Nformel();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.DimensionMultiplikation <em>Dimension Multiplikation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dimension Multiplikation</em>'.
   * @see hvbargen.meth.meth.DimensionMultiplikation
   * @generated
   */
  EClass getDimensionMultiplikation();

  /**
   * Returns the meta object for the containment reference '{@link hvbargen.meth.meth.DimensionMultiplikation#getLinks <em>Links</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Links</em>'.
   * @see hvbargen.meth.meth.DimensionMultiplikation#getLinks()
   * @see #getDimensionMultiplikation()
   * @generated
   */
  EReference getDimensionMultiplikation_Links();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.DimensionMultiplikation#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see hvbargen.meth.meth.DimensionMultiplikation#getOperator()
   * @see #getDimensionMultiplikation()
   * @generated
   */
  EAttribute getDimensionMultiplikation_Operator();

  /**
   * Returns the meta object for the containment reference '{@link hvbargen.meth.meth.DimensionMultiplikation#getRechts <em>Rechts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rechts</em>'.
   * @see hvbargen.meth.meth.DimensionMultiplikation#getRechts()
   * @see #getDimensionMultiplikation()
   * @generated
   */
  EReference getDimensionMultiplikation_Rechts();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.EinheitAddition <em>Einheit Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Einheit Addition</em>'.
   * @see hvbargen.meth.meth.EinheitAddition
   * @generated
   */
  EClass getEinheitAddition();

  /**
   * Returns the meta object for the containment reference '{@link hvbargen.meth.meth.EinheitAddition#getLinks <em>Links</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Links</em>'.
   * @see hvbargen.meth.meth.EinheitAddition#getLinks()
   * @see #getEinheitAddition()
   * @generated
   */
  EReference getEinheitAddition_Links();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.EinheitAddition#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see hvbargen.meth.meth.EinheitAddition#getOperator()
   * @see #getEinheitAddition()
   * @generated
   */
  EAttribute getEinheitAddition_Operator();

  /**
   * Returns the meta object for the containment reference '{@link hvbargen.meth.meth.EinheitAddition#getRechts <em>Rechts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rechts</em>'.
   * @see hvbargen.meth.meth.EinheitAddition#getRechts()
   * @see #getEinheitAddition()
   * @generated
   */
  EReference getEinheitAddition_Rechts();

  /**
   * Returns the meta object for class '{@link hvbargen.meth.meth.EinheitMultiplikation <em>Einheit Multiplikation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Einheit Multiplikation</em>'.
   * @see hvbargen.meth.meth.EinheitMultiplikation
   * @generated
   */
  EClass getEinheitMultiplikation();

  /**
   * Returns the meta object for the containment reference '{@link hvbargen.meth.meth.EinheitMultiplikation#getLinks <em>Links</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Links</em>'.
   * @see hvbargen.meth.meth.EinheitMultiplikation#getLinks()
   * @see #getEinheitMultiplikation()
   * @generated
   */
  EReference getEinheitMultiplikation_Links();

  /**
   * Returns the meta object for the attribute '{@link hvbargen.meth.meth.EinheitMultiplikation#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see hvbargen.meth.meth.EinheitMultiplikation#getOperator()
   * @see #getEinheitMultiplikation()
   * @generated
   */
  EAttribute getEinheitMultiplikation_Operator();

  /**
   * Returns the meta object for the containment reference '{@link hvbargen.meth.meth.EinheitMultiplikation#getRechts <em>Rechts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rechts</em>'.
   * @see hvbargen.meth.meth.EinheitMultiplikation#getRechts()
   * @see #getEinheitMultiplikation()
   * @generated
   */
  EReference getEinheitMultiplikation_Rechts();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MethFactory getMethFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.ModelImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Einheitensystem</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__EINHEITENSYSTEM = eINSTANCE.getModel_Einheitensystem();

    /**
     * The meta object literal for the '<em><b>Methoden</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__METHODEN = eINSTANCE.getModel_Methoden();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.EinheitensystemImpl <em>Einheitensystem</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.EinheitensystemImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getEinheitensystem()
     * @generated
     */
    EClass EINHEITENSYSTEM = eINSTANCE.getEinheitensystem();

    /**
     * The meta object literal for the '<em><b>Deklarationen</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EINHEITENSYSTEM__DEKLARATIONEN = eINSTANCE.getEinheitensystem_Deklarationen();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.DeklarationImpl <em>Deklaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.DeklarationImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getDeklaration()
     * @generated
     */
    EClass DEKLARATION = eINSTANCE.getDeklaration();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.DimensionImpl <em>Dimension</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.DimensionImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getDimension()
     * @generated
     */
    EClass DIMENSION = eINSTANCE.getDimension();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIMENSION__NAME = eINSTANCE.getDimension_Name();

    /**
     * The meta object literal for the '<em><b>Basis</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIMENSION__BASIS = eINSTANCE.getDimension_Basis();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.DimensionExprImpl <em>Dimension Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.DimensionExprImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getDimensionExpr()
     * @generated
     */
    EClass DIMENSION_EXPR = eINSTANCE.getDimensionExpr();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIMENSION_EXPR__REF = eINSTANCE.getDimensionExpr_Ref();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.EinheitImpl <em>Einheit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.EinheitImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getEinheit()
     * @generated
     */
    EClass EINHEIT = eINSTANCE.getEinheit();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EINHEIT__NAME = eINSTANCE.getEinheit_Name();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EINHEIT__REF = eINSTANCE.getEinheit_Ref();

    /**
     * The meta object literal for the '<em><b>Faktor</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EINHEIT__FAKTOR = eINSTANCE.getEinheit_Faktor();

    /**
     * The meta object literal for the '<em><b>Basiseinheit</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EINHEIT__BASISEINHEIT = eINSTANCE.getEinheit_Basiseinheit();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.UmrechnungImpl <em>Umrechnung</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.UmrechnungImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getUmrechnung()
     * @generated
     */
    EClass UMRECHNUNG = eINSTANCE.getUmrechnung();

    /**
     * The meta object literal for the '<em><b>Varname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UMRECHNUNG__VARNAME = eINSTANCE.getUmrechnung_Varname();

    /**
     * The meta object literal for the '<em><b>Von Einheit</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UMRECHNUNG__VON_EINHEIT = eINSTANCE.getUmrechnung_VonEinheit();

    /**
     * The meta object literal for the '<em><b>Ausdruck</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UMRECHNUNG__AUSDRUCK = eINSTANCE.getUmrechnung_Ausdruck();

    /**
     * The meta object literal for the '<em><b>Nach Einheit</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UMRECHNUNG__NACH_EINHEIT = eINSTANCE.getUmrechnung_NachEinheit();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.KonstanteImpl <em>Konstante</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.KonstanteImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getKonstante()
     * @generated
     */
    EClass KONSTANTE = eINSTANCE.getKonstante();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute KONSTANTE__NAME = eINSTANCE.getKonstante_Name();

    /**
     * The meta object literal for the '<em><b>Ausdruck</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KONSTANTE__AUSDRUCK = eINSTANCE.getKonstante_Ausdruck();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.ZahlImpl <em>Zahl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.ZahlImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getZahl()
     * @generated
     */
    EClass ZAHL = eINSTANCE.getZahl();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.GanzzahlImpl <em>Ganzzahl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.GanzzahlImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getGanzzahl()
     * @generated
     */
    EClass GANZZAHL = eINSTANCE.getGanzzahl();

    /**
     * The meta object literal for the '<em><b>Iwert</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GANZZAHL__IWERT = eINSTANCE.getGanzzahl_Iwert();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.DezimalzahlImpl <em>Dezimalzahl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.DezimalzahlImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getDezimalzahl()
     * @generated
     */
    EClass DEZIMALZAHL = eINSTANCE.getDezimalzahl();

    /**
     * The meta object literal for the '<em><b>Fwert</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEZIMALZAHL__FWERT = eINSTANCE.getDezimalzahl_Fwert();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.EinheitExprImpl <em>Einheit Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.EinheitExprImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getEinheitExpr()
     * @generated
     */
    EClass EINHEIT_EXPR = eINSTANCE.getEinheitExpr();

    /**
     * The meta object literal for the '<em><b>Varref</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EINHEIT_EXPR__VARREF = eINSTANCE.getEinheitExpr_Varref();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.MethodeImpl <em>Methode</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.MethodeImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getMethode()
     * @generated
     */
    EClass METHODE = eINSTANCE.getMethode();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHODE__NAME = eINSTANCE.getMethode_Name();

    /**
     * The meta object literal for the '<em><b>Bezeichnung</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHODE__BEZEICHNUNG = eINSTANCE.getMethode_Bezeichnung();

    /**
     * The meta object literal for the '<em><b>Ablauf</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METHODE__ABLAUF = eINSTANCE.getMethode_Ablauf();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.GegebenImpl <em>Gegeben</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.GegebenImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getGegeben()
     * @generated
     */
    EClass GEGEBEN = eINSTANCE.getGegeben();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GEGEBEN__STATEMENTS = eINSTANCE.getGegeben_Statements();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.EingabeImpl <em>Eingabe</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.EingabeImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getEingabe()
     * @generated
     */
    EClass EINGABE = eINSTANCE.getEingabe();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EINGABE__STATEMENTS = eINSTANCE.getEingabe_Statements();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.BerechnungImpl <em>Berechnung</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.BerechnungImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getBerechnung()
     * @generated
     */
    EClass BERECHNUNG = eINSTANCE.getBerechnung();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BERECHNUNG__STATEMENTS = eINSTANCE.getBerechnung_Statements();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.AusgabeImpl <em>Ausgabe</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.AusgabeImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getAusgabe()
     * @generated
     */
    EClass AUSGABE = eINSTANCE.getAusgabe();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUSGABE__STATEMENTS = eINSTANCE.getAusgabe_Statements();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.GegebenStatementImpl <em>Gegeben Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.GegebenStatementImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getGegebenStatement()
     * @generated
     */
    EClass GEGEBEN_STATEMENT = eINSTANCE.getGegebenStatement();

    /**
     * The meta object literal for the '<em><b>Eingabename</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GEGEBEN_STATEMENT__EINGABENAME = eINSTANCE.getGegebenStatement_Eingabename();

    /**
     * The meta object literal for the '<em><b>Einheit</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GEGEBEN_STATEMENT__EINHEIT = eINSTANCE.getGegebenStatement_Einheit();

    /**
     * The meta object literal for the '<em><b>Ref Methode</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GEGEBEN_STATEMENT__REF_METHODE = eINSTANCE.getGegebenStatement_RefMethode();

    /**
     * The meta object literal for the '<em><b>Bezeichnung</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GEGEBEN_STATEMENT__BEZEICHNUNG = eINSTANCE.getGegebenStatement_Bezeichnung();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.EingabeStatementImpl <em>Eingabe Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.EingabeStatementImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getEingabeStatement()
     * @generated
     */
    EClass EINGABE_STATEMENT = eINSTANCE.getEingabeStatement();

    /**
     * The meta object literal for the '<em><b>Eingabename</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EINGABE_STATEMENT__EINGABENAME = eINSTANCE.getEingabeStatement_Eingabename();

    /**
     * The meta object literal for the '<em><b>Einheit</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EINGABE_STATEMENT__EINHEIT = eINSTANCE.getEingabeStatement_Einheit();

    /**
     * The meta object literal for the '<em><b>Bezeichnung</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EINGABE_STATEMENT__BEZEICHNUNG = eINSTANCE.getEingabeStatement_Bezeichnung();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.BerechnungStatementImpl <em>Berechnung Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.BerechnungStatementImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getBerechnungStatement()
     * @generated
     */
    EClass BERECHNUNG_STATEMENT = eINSTANCE.getBerechnungStatement();

    /**
     * The meta object literal for the '<em><b>Berechnungname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BERECHNUNG_STATEMENT__BERECHNUNGNAME = eINSTANCE.getBerechnungStatement_Berechnungname();

    /**
     * The meta object literal for the '<em><b>Formel</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BERECHNUNG_STATEMENT__FORMEL = eINSTANCE.getBerechnungStatement_Formel();

    /**
     * The meta object literal for the '<em><b>Bezeichnung</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BERECHNUNG_STATEMENT__BEZEICHNUNG = eINSTANCE.getBerechnungStatement_Bezeichnung();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.AusgabeStatementImpl <em>Ausgabe Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.AusgabeStatementImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getAusgabeStatement()
     * @generated
     */
    EClass AUSGABE_STATEMENT = eINSTANCE.getAusgabeStatement();

    /**
     * The meta object literal for the '<em><b>Ausgabename</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUSGABE_STATEMENT__AUSGABENAME = eINSTANCE.getAusgabeStatement_Ausgabename();

    /**
     * The meta object literal for the '<em><b>Einheit</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUSGABE_STATEMENT__EINHEIT = eINSTANCE.getAusgabeStatement_Einheit();

    /**
     * The meta object literal for the '<em><b>Bezeichnung</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUSGABE_STATEMENT__BEZEICHNUNG = eINSTANCE.getAusgabeStatement_Bezeichnung();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.FormelImpl <em>Formel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.FormelImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getFormel()
     * @generated
     */
    EClass FORMEL = eINSTANCE.getFormel();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.TextFormelImpl <em>Text Formel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.TextFormelImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getTextFormel()
     * @generated
     */
    EClass TEXT_FORMEL = eINSTANCE.getTextFormel();

    /**
     * The meta object literal for the '<em><b>Tformel</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_FORMEL__TFORMEL = eINSTANCE.getTextFormel_Tformel();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.NumFormelImpl <em>Num Formel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.NumFormelImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getNumFormel()
     * @generated
     */
    EClass NUM_FORMEL = eINSTANCE.getNumFormel();

    /**
     * The meta object literal for the '<em><b>Nformel</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NUM_FORMEL__NFORMEL = eINSTANCE.getNumFormel_Nformel();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.DimensionMultiplikationImpl <em>Dimension Multiplikation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.DimensionMultiplikationImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getDimensionMultiplikation()
     * @generated
     */
    EClass DIMENSION_MULTIPLIKATION = eINSTANCE.getDimensionMultiplikation();

    /**
     * The meta object literal for the '<em><b>Links</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIMENSION_MULTIPLIKATION__LINKS = eINSTANCE.getDimensionMultiplikation_Links();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIMENSION_MULTIPLIKATION__OPERATOR = eINSTANCE.getDimensionMultiplikation_Operator();

    /**
     * The meta object literal for the '<em><b>Rechts</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIMENSION_MULTIPLIKATION__RECHTS = eINSTANCE.getDimensionMultiplikation_Rechts();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.EinheitAdditionImpl <em>Einheit Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.EinheitAdditionImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getEinheitAddition()
     * @generated
     */
    EClass EINHEIT_ADDITION = eINSTANCE.getEinheitAddition();

    /**
     * The meta object literal for the '<em><b>Links</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EINHEIT_ADDITION__LINKS = eINSTANCE.getEinheitAddition_Links();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EINHEIT_ADDITION__OPERATOR = eINSTANCE.getEinheitAddition_Operator();

    /**
     * The meta object literal for the '<em><b>Rechts</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EINHEIT_ADDITION__RECHTS = eINSTANCE.getEinheitAddition_Rechts();

    /**
     * The meta object literal for the '{@link hvbargen.meth.meth.impl.EinheitMultiplikationImpl <em>Einheit Multiplikation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hvbargen.meth.meth.impl.EinheitMultiplikationImpl
     * @see hvbargen.meth.meth.impl.MethPackageImpl#getEinheitMultiplikation()
     * @generated
     */
    EClass EINHEIT_MULTIPLIKATION = eINSTANCE.getEinheitMultiplikation();

    /**
     * The meta object literal for the '<em><b>Links</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EINHEIT_MULTIPLIKATION__LINKS = eINSTANCE.getEinheitMultiplikation_Links();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EINHEIT_MULTIPLIKATION__OPERATOR = eINSTANCE.getEinheitMultiplikation_Operator();

    /**
     * The meta object literal for the '<em><b>Rechts</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EINHEIT_MULTIPLIKATION__RECHTS = eINSTANCE.getEinheitMultiplikation_Rechts();

  }

} //MethPackage
