/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hvbargen.meth.meth.Model#getEinheitensystem <em>Einheitensystem</em>}</li>
 *   <li>{@link hvbargen.meth.meth.Model#getMethoden <em>Methoden</em>}</li>
 * </ul>
 *
 * @see hvbargen.meth.meth.MethPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Einheitensystem</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Einheitensystem</em>' containment reference.
   * @see #setEinheitensystem(Einheitensystem)
   * @see hvbargen.meth.meth.MethPackage#getModel_Einheitensystem()
   * @model containment="true"
   * @generated
   */
  Einheitensystem getEinheitensystem();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.Model#getEinheitensystem <em>Einheitensystem</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Einheitensystem</em>' containment reference.
   * @see #getEinheitensystem()
   * @generated
   */
  void setEinheitensystem(Einheitensystem value);

  /**
   * Returns the value of the '<em><b>Methoden</b></em>' containment reference list.
   * The list contents are of type {@link hvbargen.meth.meth.Methode}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Methoden</em>' containment reference list.
   * @see hvbargen.meth.meth.MethPackage#getModel_Methoden()
   * @model containment="true"
   * @generated
   */
  EList<Methode> getMethoden();

} // Model
