/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Umrechnung</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hvbargen.meth.meth.Umrechnung#getVarname <em>Varname</em>}</li>
 *   <li>{@link hvbargen.meth.meth.Umrechnung#getVonEinheit <em>Von Einheit</em>}</li>
 *   <li>{@link hvbargen.meth.meth.Umrechnung#getAusdruck <em>Ausdruck</em>}</li>
 *   <li>{@link hvbargen.meth.meth.Umrechnung#getNachEinheit <em>Nach Einheit</em>}</li>
 * </ul>
 *
 * @see hvbargen.meth.meth.MethPackage#getUmrechnung()
 * @model
 * @generated
 */
public interface Umrechnung extends Deklaration
{
  /**
   * Returns the value of the '<em><b>Varname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Varname</em>' attribute.
   * @see #setVarname(String)
   * @see hvbargen.meth.meth.MethPackage#getUmrechnung_Varname()
   * @model
   * @generated
   */
  String getVarname();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.Umrechnung#getVarname <em>Varname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Varname</em>' attribute.
   * @see #getVarname()
   * @generated
   */
  void setVarname(String value);

  /**
   * Returns the value of the '<em><b>Von Einheit</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Von Einheit</em>' reference.
   * @see #setVonEinheit(Einheit)
   * @see hvbargen.meth.meth.MethPackage#getUmrechnung_VonEinheit()
   * @model
   * @generated
   */
  Einheit getVonEinheit();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.Umrechnung#getVonEinheit <em>Von Einheit</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Von Einheit</em>' reference.
   * @see #getVonEinheit()
   * @generated
   */
  void setVonEinheit(Einheit value);

  /**
   * Returns the value of the '<em><b>Ausdruck</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ausdruck</em>' containment reference.
   * @see #setAusdruck(EinheitExpr)
   * @see hvbargen.meth.meth.MethPackage#getUmrechnung_Ausdruck()
   * @model containment="true"
   * @generated
   */
  EinheitExpr getAusdruck();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.Umrechnung#getAusdruck <em>Ausdruck</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ausdruck</em>' containment reference.
   * @see #getAusdruck()
   * @generated
   */
  void setAusdruck(EinheitExpr value);

  /**
   * Returns the value of the '<em><b>Nach Einheit</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nach Einheit</em>' reference.
   * @see #setNachEinheit(Einheit)
   * @see hvbargen.meth.meth.MethPackage#getUmrechnung_NachEinheit()
   * @model
   * @generated
   */
  Einheit getNachEinheit();

  /**
   * Sets the value of the '{@link hvbargen.meth.meth.Umrechnung#getNachEinheit <em>Nach Einheit</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nach Einheit</em>' reference.
   * @see #getNachEinheit()
   * @generated
   */
  void setNachEinheit(Einheit value);

} // Umrechnung
