/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Zahl</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hvbargen.meth.meth.MethPackage#getZahl()
 * @model
 * @generated
 */
public interface Zahl extends EinheitExpr
{
} // Zahl
