/*
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MethAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("hvbargen/meth/parser/antlr/internal/InternalMeth.tokens");
	}
}
