/*
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import hvbargen.meth.MethRuntimeModule;
import hvbargen.meth.MethStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MethIdeSetup extends MethStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MethRuntimeModule(), new MethIdeModule()));
	}
	
}
