/*
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.ui.tests;

import com.google.inject.Injector;
import hvbargen.meth.ui.internal.MethActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MethUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MethActivator.getInstance().getInjector("hvbargen.meth.Meth");
	}

}
