/*
 * generated by Xtext 2.26.0
 */
package hvbargen.meth;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MethRuntimeModule extends AbstractMethRuntimeModule {
}
