/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth.impl;

import hvbargen.meth.meth.AusgabeStatement;
import hvbargen.meth.meth.EinheitExpr;
import hvbargen.meth.meth.MethPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ausgabe Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link hvbargen.meth.meth.impl.AusgabeStatementImpl#getAusgabename <em>Ausgabename</em>}</li>
 *   <li>{@link hvbargen.meth.meth.impl.AusgabeStatementImpl#getEinheit <em>Einheit</em>}</li>
 *   <li>{@link hvbargen.meth.meth.impl.AusgabeStatementImpl#getBezeichnung <em>Bezeichnung</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AusgabeStatementImpl extends MinimalEObjectImpl.Container implements AusgabeStatement
{
  /**
   * The default value of the '{@link #getAusgabename() <em>Ausgabename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAusgabename()
   * @generated
   * @ordered
   */
  protected static final String AUSGABENAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAusgabename() <em>Ausgabename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAusgabename()
   * @generated
   * @ordered
   */
  protected String ausgabename = AUSGABENAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getEinheit() <em>Einheit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEinheit()
   * @generated
   * @ordered
   */
  protected EinheitExpr einheit;

  /**
   * The default value of the '{@link #getBezeichnung() <em>Bezeichnung</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBezeichnung()
   * @generated
   * @ordered
   */
  protected static final String BEZEICHNUNG_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBezeichnung() <em>Bezeichnung</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBezeichnung()
   * @generated
   * @ordered
   */
  protected String bezeichnung = BEZEICHNUNG_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AusgabeStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MethPackage.Literals.AUSGABE_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAusgabename()
  {
    return ausgabename;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAusgabename(String newAusgabename)
  {
    String oldAusgabename = ausgabename;
    ausgabename = newAusgabename;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MethPackage.AUSGABE_STATEMENT__AUSGABENAME, oldAusgabename, ausgabename));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EinheitExpr getEinheit()
  {
    return einheit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEinheit(EinheitExpr newEinheit, NotificationChain msgs)
  {
    EinheitExpr oldEinheit = einheit;
    einheit = newEinheit;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MethPackage.AUSGABE_STATEMENT__EINHEIT, oldEinheit, newEinheit);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEinheit(EinheitExpr newEinheit)
  {
    if (newEinheit != einheit)
    {
      NotificationChain msgs = null;
      if (einheit != null)
        msgs = ((InternalEObject)einheit).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MethPackage.AUSGABE_STATEMENT__EINHEIT, null, msgs);
      if (newEinheit != null)
        msgs = ((InternalEObject)newEinheit).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MethPackage.AUSGABE_STATEMENT__EINHEIT, null, msgs);
      msgs = basicSetEinheit(newEinheit, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MethPackage.AUSGABE_STATEMENT__EINHEIT, newEinheit, newEinheit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getBezeichnung()
  {
    return bezeichnung;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBezeichnung(String newBezeichnung)
  {
    String oldBezeichnung = bezeichnung;
    bezeichnung = newBezeichnung;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MethPackage.AUSGABE_STATEMENT__BEZEICHNUNG, oldBezeichnung, bezeichnung));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MethPackage.AUSGABE_STATEMENT__EINHEIT:
        return basicSetEinheit(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MethPackage.AUSGABE_STATEMENT__AUSGABENAME:
        return getAusgabename();
      case MethPackage.AUSGABE_STATEMENT__EINHEIT:
        return getEinheit();
      case MethPackage.AUSGABE_STATEMENT__BEZEICHNUNG:
        return getBezeichnung();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MethPackage.AUSGABE_STATEMENT__AUSGABENAME:
        setAusgabename((String)newValue);
        return;
      case MethPackage.AUSGABE_STATEMENT__EINHEIT:
        setEinheit((EinheitExpr)newValue);
        return;
      case MethPackage.AUSGABE_STATEMENT__BEZEICHNUNG:
        setBezeichnung((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MethPackage.AUSGABE_STATEMENT__AUSGABENAME:
        setAusgabename(AUSGABENAME_EDEFAULT);
        return;
      case MethPackage.AUSGABE_STATEMENT__EINHEIT:
        setEinheit((EinheitExpr)null);
        return;
      case MethPackage.AUSGABE_STATEMENT__BEZEICHNUNG:
        setBezeichnung(BEZEICHNUNG_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MethPackage.AUSGABE_STATEMENT__AUSGABENAME:
        return AUSGABENAME_EDEFAULT == null ? ausgabename != null : !AUSGABENAME_EDEFAULT.equals(ausgabename);
      case MethPackage.AUSGABE_STATEMENT__EINHEIT:
        return einheit != null;
      case MethPackage.AUSGABE_STATEMENT__BEZEICHNUNG:
        return BEZEICHNUNG_EDEFAULT == null ? bezeichnung != null : !BEZEICHNUNG_EDEFAULT.equals(bezeichnung);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ausgabename: ");
    result.append(ausgabename);
    result.append(", bezeichnung: ");
    result.append(bezeichnung);
    result.append(')');
    return result.toString();
  }

} //AusgabeStatementImpl
