/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth.impl;

import hvbargen.meth.meth.Deklaration;
import hvbargen.meth.meth.Einheitensystem;
import hvbargen.meth.meth.MethPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Einheitensystem</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link hvbargen.meth.meth.impl.EinheitensystemImpl#getDeklarationen <em>Deklarationen</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EinheitensystemImpl extends MinimalEObjectImpl.Container implements Einheitensystem
{
  /**
   * The cached value of the '{@link #getDeklarationen() <em>Deklarationen</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeklarationen()
   * @generated
   * @ordered
   */
  protected EList<Deklaration> deklarationen;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EinheitensystemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MethPackage.Literals.EINHEITENSYSTEM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Deklaration> getDeklarationen()
  {
    if (deklarationen == null)
    {
      deklarationen = new EObjectContainmentEList<Deklaration>(Deklaration.class, this, MethPackage.EINHEITENSYSTEM__DEKLARATIONEN);
    }
    return deklarationen;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MethPackage.EINHEITENSYSTEM__DEKLARATIONEN:
        return ((InternalEList<?>)getDeklarationen()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MethPackage.EINHEITENSYSTEM__DEKLARATIONEN:
        return getDeklarationen();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MethPackage.EINHEITENSYSTEM__DEKLARATIONEN:
        getDeklarationen().clear();
        getDeklarationen().addAll((Collection<? extends Deklaration>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MethPackage.EINHEITENSYSTEM__DEKLARATIONEN:
        getDeklarationen().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MethPackage.EINHEITENSYSTEM__DEKLARATIONEN:
        return deklarationen != null && !deklarationen.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //EinheitensystemImpl
