/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth.impl;

import hvbargen.meth.meth.Dimension;
import hvbargen.meth.meth.Einheit;
import hvbargen.meth.meth.EinheitExpr;
import hvbargen.meth.meth.MethPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Einheit</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link hvbargen.meth.meth.impl.EinheitImpl#getName <em>Name</em>}</li>
 *   <li>{@link hvbargen.meth.meth.impl.EinheitImpl#getRef <em>Ref</em>}</li>
 *   <li>{@link hvbargen.meth.meth.impl.EinheitImpl#getFaktor <em>Faktor</em>}</li>
 *   <li>{@link hvbargen.meth.meth.impl.EinheitImpl#getBasiseinheit <em>Basiseinheit</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EinheitImpl extends DeklarationImpl implements Einheit
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getRef() <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRef()
   * @generated
   * @ordered
   */
  protected Dimension ref;

  /**
   * The cached value of the '{@link #getFaktor() <em>Faktor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFaktor()
   * @generated
   * @ordered
   */
  protected EinheitExpr faktor;

  /**
   * The cached value of the '{@link #getBasiseinheit() <em>Basiseinheit</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBasiseinheit()
   * @generated
   * @ordered
   */
  protected Einheit basiseinheit;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EinheitImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MethPackage.Literals.EINHEIT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MethPackage.EINHEIT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Dimension getRef()
  {
    if (ref != null && ref.eIsProxy())
    {
      InternalEObject oldRef = (InternalEObject)ref;
      ref = (Dimension)eResolveProxy(oldRef);
      if (ref != oldRef)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MethPackage.EINHEIT__REF, oldRef, ref));
      }
    }
    return ref;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Dimension basicGetRef()
  {
    return ref;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRef(Dimension newRef)
  {
    Dimension oldRef = ref;
    ref = newRef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MethPackage.EINHEIT__REF, oldRef, ref));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EinheitExpr getFaktor()
  {
    return faktor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFaktor(EinheitExpr newFaktor, NotificationChain msgs)
  {
    EinheitExpr oldFaktor = faktor;
    faktor = newFaktor;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MethPackage.EINHEIT__FAKTOR, oldFaktor, newFaktor);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFaktor(EinheitExpr newFaktor)
  {
    if (newFaktor != faktor)
    {
      NotificationChain msgs = null;
      if (faktor != null)
        msgs = ((InternalEObject)faktor).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MethPackage.EINHEIT__FAKTOR, null, msgs);
      if (newFaktor != null)
        msgs = ((InternalEObject)newFaktor).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MethPackage.EINHEIT__FAKTOR, null, msgs);
      msgs = basicSetFaktor(newFaktor, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MethPackage.EINHEIT__FAKTOR, newFaktor, newFaktor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Einheit getBasiseinheit()
  {
    if (basiseinheit != null && basiseinheit.eIsProxy())
    {
      InternalEObject oldBasiseinheit = (InternalEObject)basiseinheit;
      basiseinheit = (Einheit)eResolveProxy(oldBasiseinheit);
      if (basiseinheit != oldBasiseinheit)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MethPackage.EINHEIT__BASISEINHEIT, oldBasiseinheit, basiseinheit));
      }
    }
    return basiseinheit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Einheit basicGetBasiseinheit()
  {
    return basiseinheit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBasiseinheit(Einheit newBasiseinheit)
  {
    Einheit oldBasiseinheit = basiseinheit;
    basiseinheit = newBasiseinheit;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MethPackage.EINHEIT__BASISEINHEIT, oldBasiseinheit, basiseinheit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MethPackage.EINHEIT__FAKTOR:
        return basicSetFaktor(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MethPackage.EINHEIT__NAME:
        return getName();
      case MethPackage.EINHEIT__REF:
        if (resolve) return getRef();
        return basicGetRef();
      case MethPackage.EINHEIT__FAKTOR:
        return getFaktor();
      case MethPackage.EINHEIT__BASISEINHEIT:
        if (resolve) return getBasiseinheit();
        return basicGetBasiseinheit();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MethPackage.EINHEIT__NAME:
        setName((String)newValue);
        return;
      case MethPackage.EINHEIT__REF:
        setRef((Dimension)newValue);
        return;
      case MethPackage.EINHEIT__FAKTOR:
        setFaktor((EinheitExpr)newValue);
        return;
      case MethPackage.EINHEIT__BASISEINHEIT:
        setBasiseinheit((Einheit)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MethPackage.EINHEIT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MethPackage.EINHEIT__REF:
        setRef((Dimension)null);
        return;
      case MethPackage.EINHEIT__FAKTOR:
        setFaktor((EinheitExpr)null);
        return;
      case MethPackage.EINHEIT__BASISEINHEIT:
        setBasiseinheit((Einheit)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MethPackage.EINHEIT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MethPackage.EINHEIT__REF:
        return ref != null;
      case MethPackage.EINHEIT__FAKTOR:
        return faktor != null;
      case MethPackage.EINHEIT__BASISEINHEIT:
        return basiseinheit != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //EinheitImpl
