/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth.impl;

import hvbargen.meth.meth.EinheitExpr;
import hvbargen.meth.meth.GegebenStatement;
import hvbargen.meth.meth.MethPackage;
import hvbargen.meth.meth.Methode;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Gegeben Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link hvbargen.meth.meth.impl.GegebenStatementImpl#getEingabename <em>Eingabename</em>}</li>
 *   <li>{@link hvbargen.meth.meth.impl.GegebenStatementImpl#getEinheit <em>Einheit</em>}</li>
 *   <li>{@link hvbargen.meth.meth.impl.GegebenStatementImpl#getRefMethode <em>Ref Methode</em>}</li>
 *   <li>{@link hvbargen.meth.meth.impl.GegebenStatementImpl#getBezeichnung <em>Bezeichnung</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GegebenStatementImpl extends MinimalEObjectImpl.Container implements GegebenStatement
{
  /**
   * The default value of the '{@link #getEingabename() <em>Eingabename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEingabename()
   * @generated
   * @ordered
   */
  protected static final String EINGABENAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEingabename() <em>Eingabename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEingabename()
   * @generated
   * @ordered
   */
  protected String eingabename = EINGABENAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getEinheit() <em>Einheit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEinheit()
   * @generated
   * @ordered
   */
  protected EinheitExpr einheit;

  /**
   * The cached value of the '{@link #getRefMethode() <em>Ref Methode</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRefMethode()
   * @generated
   * @ordered
   */
  protected Methode refMethode;

  /**
   * The default value of the '{@link #getBezeichnung() <em>Bezeichnung</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBezeichnung()
   * @generated
   * @ordered
   */
  protected static final String BEZEICHNUNG_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBezeichnung() <em>Bezeichnung</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBezeichnung()
   * @generated
   * @ordered
   */
  protected String bezeichnung = BEZEICHNUNG_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GegebenStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MethPackage.Literals.GEGEBEN_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getEingabename()
  {
    return eingabename;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEingabename(String newEingabename)
  {
    String oldEingabename = eingabename;
    eingabename = newEingabename;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MethPackage.GEGEBEN_STATEMENT__EINGABENAME, oldEingabename, eingabename));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EinheitExpr getEinheit()
  {
    return einheit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEinheit(EinheitExpr newEinheit, NotificationChain msgs)
  {
    EinheitExpr oldEinheit = einheit;
    einheit = newEinheit;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MethPackage.GEGEBEN_STATEMENT__EINHEIT, oldEinheit, newEinheit);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEinheit(EinheitExpr newEinheit)
  {
    if (newEinheit != einheit)
    {
      NotificationChain msgs = null;
      if (einheit != null)
        msgs = ((InternalEObject)einheit).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MethPackage.GEGEBEN_STATEMENT__EINHEIT, null, msgs);
      if (newEinheit != null)
        msgs = ((InternalEObject)newEinheit).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MethPackage.GEGEBEN_STATEMENT__EINHEIT, null, msgs);
      msgs = basicSetEinheit(newEinheit, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MethPackage.GEGEBEN_STATEMENT__EINHEIT, newEinheit, newEinheit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Methode getRefMethode()
  {
    if (refMethode != null && refMethode.eIsProxy())
    {
      InternalEObject oldRefMethode = (InternalEObject)refMethode;
      refMethode = (Methode)eResolveProxy(oldRefMethode);
      if (refMethode != oldRefMethode)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MethPackage.GEGEBEN_STATEMENT__REF_METHODE, oldRefMethode, refMethode));
      }
    }
    return refMethode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Methode basicGetRefMethode()
  {
    return refMethode;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRefMethode(Methode newRefMethode)
  {
    Methode oldRefMethode = refMethode;
    refMethode = newRefMethode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MethPackage.GEGEBEN_STATEMENT__REF_METHODE, oldRefMethode, refMethode));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getBezeichnung()
  {
    return bezeichnung;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBezeichnung(String newBezeichnung)
  {
    String oldBezeichnung = bezeichnung;
    bezeichnung = newBezeichnung;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MethPackage.GEGEBEN_STATEMENT__BEZEICHNUNG, oldBezeichnung, bezeichnung));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MethPackage.GEGEBEN_STATEMENT__EINHEIT:
        return basicSetEinheit(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MethPackage.GEGEBEN_STATEMENT__EINGABENAME:
        return getEingabename();
      case MethPackage.GEGEBEN_STATEMENT__EINHEIT:
        return getEinheit();
      case MethPackage.GEGEBEN_STATEMENT__REF_METHODE:
        if (resolve) return getRefMethode();
        return basicGetRefMethode();
      case MethPackage.GEGEBEN_STATEMENT__BEZEICHNUNG:
        return getBezeichnung();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MethPackage.GEGEBEN_STATEMENT__EINGABENAME:
        setEingabename((String)newValue);
        return;
      case MethPackage.GEGEBEN_STATEMENT__EINHEIT:
        setEinheit((EinheitExpr)newValue);
        return;
      case MethPackage.GEGEBEN_STATEMENT__REF_METHODE:
        setRefMethode((Methode)newValue);
        return;
      case MethPackage.GEGEBEN_STATEMENT__BEZEICHNUNG:
        setBezeichnung((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MethPackage.GEGEBEN_STATEMENT__EINGABENAME:
        setEingabename(EINGABENAME_EDEFAULT);
        return;
      case MethPackage.GEGEBEN_STATEMENT__EINHEIT:
        setEinheit((EinheitExpr)null);
        return;
      case MethPackage.GEGEBEN_STATEMENT__REF_METHODE:
        setRefMethode((Methode)null);
        return;
      case MethPackage.GEGEBEN_STATEMENT__BEZEICHNUNG:
        setBezeichnung(BEZEICHNUNG_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MethPackage.GEGEBEN_STATEMENT__EINGABENAME:
        return EINGABENAME_EDEFAULT == null ? eingabename != null : !EINGABENAME_EDEFAULT.equals(eingabename);
      case MethPackage.GEGEBEN_STATEMENT__EINHEIT:
        return einheit != null;
      case MethPackage.GEGEBEN_STATEMENT__REF_METHODE:
        return refMethode != null;
      case MethPackage.GEGEBEN_STATEMENT__BEZEICHNUNG:
        return BEZEICHNUNG_EDEFAULT == null ? bezeichnung != null : !BEZEICHNUNG_EDEFAULT.equals(bezeichnung);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (eingabename: ");
    result.append(eingabename);
    result.append(", bezeichnung: ");
    result.append(bezeichnung);
    result.append(')');
    return result.toString();
  }

} //GegebenStatementImpl
