/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth.impl;

import hvbargen.meth.meth.EinheitExpr;
import hvbargen.meth.meth.MethPackage;
import hvbargen.meth.meth.NumFormel;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Num Formel</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link hvbargen.meth.meth.impl.NumFormelImpl#getNformel <em>Nformel</em>}</li>
 * </ul>
 *
 * @generated
 */
public class NumFormelImpl extends FormelImpl implements NumFormel
{
  /**
   * The cached value of the '{@link #getNformel() <em>Nformel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNformel()
   * @generated
   * @ordered
   */
  protected EinheitExpr nformel;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NumFormelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MethPackage.Literals.NUM_FORMEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EinheitExpr getNformel()
  {
    return nformel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNformel(EinheitExpr newNformel, NotificationChain msgs)
  {
    EinheitExpr oldNformel = nformel;
    nformel = newNformel;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MethPackage.NUM_FORMEL__NFORMEL, oldNformel, newNformel);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNformel(EinheitExpr newNformel)
  {
    if (newNformel != nformel)
    {
      NotificationChain msgs = null;
      if (nformel != null)
        msgs = ((InternalEObject)nformel).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MethPackage.NUM_FORMEL__NFORMEL, null, msgs);
      if (newNformel != null)
        msgs = ((InternalEObject)newNformel).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MethPackage.NUM_FORMEL__NFORMEL, null, msgs);
      msgs = basicSetNformel(newNformel, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MethPackage.NUM_FORMEL__NFORMEL, newNformel, newNformel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MethPackage.NUM_FORMEL__NFORMEL:
        return basicSetNformel(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MethPackage.NUM_FORMEL__NFORMEL:
        return getNformel();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MethPackage.NUM_FORMEL__NFORMEL:
        setNformel((EinheitExpr)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MethPackage.NUM_FORMEL__NFORMEL:
        setNformel((EinheitExpr)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MethPackage.NUM_FORMEL__NFORMEL:
        return nformel != null;
    }
    return super.eIsSet(featureID);
  }

} //NumFormelImpl
