/**
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.meth.util;

import hvbargen.meth.meth.*;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see hvbargen.meth.meth.MethPackage
 * @generated
 */
public class MethSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static MethPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MethSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = MethPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case MethPackage.MODEL:
      {
        Model model = (Model)theEObject;
        T result = caseModel(model);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.EINHEITENSYSTEM:
      {
        Einheitensystem einheitensystem = (Einheitensystem)theEObject;
        T result = caseEinheitensystem(einheitensystem);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.DEKLARATION:
      {
        Deklaration deklaration = (Deklaration)theEObject;
        T result = caseDeklaration(deklaration);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.DIMENSION:
      {
        Dimension dimension = (Dimension)theEObject;
        T result = caseDimension(dimension);
        if (result == null) result = caseDeklaration(dimension);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.DIMENSION_EXPR:
      {
        DimensionExpr dimensionExpr = (DimensionExpr)theEObject;
        T result = caseDimensionExpr(dimensionExpr);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.EINHEIT:
      {
        Einheit einheit = (Einheit)theEObject;
        T result = caseEinheit(einheit);
        if (result == null) result = caseDeklaration(einheit);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.UMRECHNUNG:
      {
        Umrechnung umrechnung = (Umrechnung)theEObject;
        T result = caseUmrechnung(umrechnung);
        if (result == null) result = caseDeklaration(umrechnung);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.KONSTANTE:
      {
        Konstante konstante = (Konstante)theEObject;
        T result = caseKonstante(konstante);
        if (result == null) result = caseDeklaration(konstante);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.ZAHL:
      {
        Zahl zahl = (Zahl)theEObject;
        T result = caseZahl(zahl);
        if (result == null) result = caseEinheitExpr(zahl);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.GANZZAHL:
      {
        Ganzzahl ganzzahl = (Ganzzahl)theEObject;
        T result = caseGanzzahl(ganzzahl);
        if (result == null) result = caseZahl(ganzzahl);
        if (result == null) result = caseEinheitExpr(ganzzahl);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.DEZIMALZAHL:
      {
        Dezimalzahl dezimalzahl = (Dezimalzahl)theEObject;
        T result = caseDezimalzahl(dezimalzahl);
        if (result == null) result = caseZahl(dezimalzahl);
        if (result == null) result = caseEinheitExpr(dezimalzahl);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.EINHEIT_EXPR:
      {
        EinheitExpr einheitExpr = (EinheitExpr)theEObject;
        T result = caseEinheitExpr(einheitExpr);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.METHODE:
      {
        Methode methode = (Methode)theEObject;
        T result = caseMethode(methode);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.GEGEBEN:
      {
        Gegeben gegeben = (Gegeben)theEObject;
        T result = caseGegeben(gegeben);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.EINGABE:
      {
        Eingabe eingabe = (Eingabe)theEObject;
        T result = caseEingabe(eingabe);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.BERECHNUNG:
      {
        Berechnung berechnung = (Berechnung)theEObject;
        T result = caseBerechnung(berechnung);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.AUSGABE:
      {
        Ausgabe ausgabe = (Ausgabe)theEObject;
        T result = caseAusgabe(ausgabe);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.GEGEBEN_STATEMENT:
      {
        GegebenStatement gegebenStatement = (GegebenStatement)theEObject;
        T result = caseGegebenStatement(gegebenStatement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.EINGABE_STATEMENT:
      {
        EingabeStatement eingabeStatement = (EingabeStatement)theEObject;
        T result = caseEingabeStatement(eingabeStatement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.BERECHNUNG_STATEMENT:
      {
        BerechnungStatement berechnungStatement = (BerechnungStatement)theEObject;
        T result = caseBerechnungStatement(berechnungStatement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.AUSGABE_STATEMENT:
      {
        AusgabeStatement ausgabeStatement = (AusgabeStatement)theEObject;
        T result = caseAusgabeStatement(ausgabeStatement);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.FORMEL:
      {
        Formel formel = (Formel)theEObject;
        T result = caseFormel(formel);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.TEXT_FORMEL:
      {
        TextFormel textFormel = (TextFormel)theEObject;
        T result = caseTextFormel(textFormel);
        if (result == null) result = caseFormel(textFormel);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.NUM_FORMEL:
      {
        NumFormel numFormel = (NumFormel)theEObject;
        T result = caseNumFormel(numFormel);
        if (result == null) result = caseFormel(numFormel);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.DIMENSION_MULTIPLIKATION:
      {
        DimensionMultiplikation dimensionMultiplikation = (DimensionMultiplikation)theEObject;
        T result = caseDimensionMultiplikation(dimensionMultiplikation);
        if (result == null) result = caseDimensionExpr(dimensionMultiplikation);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.EINHEIT_ADDITION:
      {
        EinheitAddition einheitAddition = (EinheitAddition)theEObject;
        T result = caseEinheitAddition(einheitAddition);
        if (result == null) result = caseEinheitExpr(einheitAddition);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MethPackage.EINHEIT_MULTIPLIKATION:
      {
        EinheitMultiplikation einheitMultiplikation = (EinheitMultiplikation)theEObject;
        T result = caseEinheitMultiplikation(einheitMultiplikation);
        if (result == null) result = caseEinheitExpr(einheitMultiplikation);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Model</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseModel(Model object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Einheitensystem</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Einheitensystem</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEinheitensystem(Einheitensystem object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Deklaration</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Deklaration</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDeklaration(Deklaration object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Dimension</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Dimension</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDimension(Dimension object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Dimension Expr</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Dimension Expr</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDimensionExpr(DimensionExpr object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Einheit</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Einheit</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEinheit(Einheit object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Umrechnung</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Umrechnung</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseUmrechnung(Umrechnung object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Konstante</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Konstante</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseKonstante(Konstante object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Zahl</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Zahl</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseZahl(Zahl object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Ganzzahl</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Ganzzahl</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseGanzzahl(Ganzzahl object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Dezimalzahl</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Dezimalzahl</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDezimalzahl(Dezimalzahl object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Einheit Expr</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Einheit Expr</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEinheitExpr(EinheitExpr object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Methode</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Methode</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMethode(Methode object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Gegeben</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Gegeben</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseGegeben(Gegeben object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Eingabe</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Eingabe</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEingabe(Eingabe object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Berechnung</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Berechnung</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBerechnung(Berechnung object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Ausgabe</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Ausgabe</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAusgabe(Ausgabe object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Gegeben Statement</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Gegeben Statement</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseGegebenStatement(GegebenStatement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Eingabe Statement</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Eingabe Statement</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEingabeStatement(EingabeStatement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Berechnung Statement</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Berechnung Statement</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBerechnungStatement(BerechnungStatement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Ausgabe Statement</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Ausgabe Statement</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAusgabeStatement(AusgabeStatement object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Formel</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Formel</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseFormel(Formel object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Text Formel</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Text Formel</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTextFormel(TextFormel object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Num Formel</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Num Formel</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseNumFormel(NumFormel object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Dimension Multiplikation</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Dimension Multiplikation</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDimensionMultiplikation(DimensionMultiplikation object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Einheit Addition</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Einheit Addition</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEinheitAddition(EinheitAddition object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Einheit Multiplikation</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Einheit Multiplikation</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseEinheitMultiplikation(EinheitMultiplikation object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //MethSwitch
