/*
 * generated by Xtext 2.26.0
 */
package hvbargen.meth.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMethScopeProvider extends DelegatingScopeProvider {
}
